### ISSUE TITLE
Your Git Hub provided war file from s1_vid1 directory reports error when deployed to tomcat 

### ISSUE THREAD

**Issue by paboulos** [eugenp/course#3]
Doesn't work in my local Tomcat. For the first example section 1 s1_vid1 does not run. I am using windows 7(64 bit) tomcat 7 (64bit)  java 8(64bit).

I first copied the provided war file spring-security.war to tomcat web app dir and it fails to run. 

I then ran from directory course-master\section1\s1_vid1>  mvn clean install
and got successful build. The copy the war file from the target directory to Tomcat 7 webapps directory and start tomcat and then go to URL http://localhost:8080/spring-security/ . The browers returns:
HTTP Status 404 - /spring%2Dsecurity/

Tomcat console  log also reports deployment error:

INFO: Deploying web application archive D:\apache\apache-tomcat-7.0.61\webapps\spring-security.war
2015-05-01 19:17:50,060 [localhost-startStop-1] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization started
2015-05-01 19:17:50,156 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext - Refreshing Root WebApplicationContex
t: startup date [Fri May 01 19:17:50 EDT 2015]; root of context hierarchy
2015-05-01 19:17:50,226 [localhost-startStop-1] INFO  o.s.c.a.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found
and supported for component scanning
2015-05-01 19:17:50,271 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext - Found 3 annotated classes in package
 [com.packt.springsecurity.frontend.spring]
2015-05-01 19:17:50,274 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext - Found 1 annotated classes in package
 [com.packt.springsecurity.backend.spring]
2015-05-01 19:17:50,342 [localhost-startStop-1] INFO  o.s.c.a.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found
and supported for component scanning
2015-05-01 19:17:50,350 [localhost-startStop-1] ERROR o.s.web.context.ContextLoader - Context initialization failed
java.lang.IllegalArgumentException: null
        at org.springframework.asm.ClassReader.<init>(Unknown Source) ~[spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.asm.ClassReader.<init>(Unknown Source) ~[spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.asm.ClassReader.<init>(Unknown Source) ~[spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:52) ~[spring-core-3.2.0.RELEASE.
jar:3.2.0.RELEASE]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80) ~[s
pring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:101)
~[spring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:76) ~[s
pring-core-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:298) ~[spring-context-3.
2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:300) ~[spring-context-3.
2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.getImports(ConfigurationClassParser.java:300) ~[spring-context-3.
2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:230) ~[
spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:153) ~[sp
ring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:130) ~[spring-context-3.2.0.R
ELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcess
or.java:285) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostPr
ocessor.java:223) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:63
0) ~[spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461) ~[spring-context-3.2.
0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383) ~[spring-web-3.2.0
.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283) ~[spring-web-3.2.0.RELEASE.jar:3.
2.0.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.0.RELEAS
E.jar:3.2.0.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016) [catalina.jar:7.0.61]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528) [catalina.jar:7.0.61]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.61]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.61]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.61]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.61]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1090) [catalina.jar:7.0.61]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1900) [catalina.jar:7.0.61]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
May 01, 2015 7:17:50 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
May 01, 2015 7:17:50 PM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [133] milliseconds.
May 01, 2015 7:17:50 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/spring-security] startup failed due to previous errors
2015-05-01 19:17:50,493 [localhost-startStop-1] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext - Closing Root WebApplicationContext:
startup date [Fri May 01 19:17:50 EDT 2015]; root of context hierarchy
2015-05-01 19:17:50,500 [localhost-startStop-1] WARN  o.s.w.c.s.AnnotationConfigWebApplicationContext - Exception thrown from ApplicationLis
tener handling ContextClosedEvent
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: Ro
ot WebApplicationContext: startup date [Fri May 01 19:17:50 EDT 2015]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:347
) [spring-context-3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) [spring-context-
3.2.0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1049) [spring-context-3.2.
0.RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [spring-context-3.2.0.
RELEASE.jar:3.2.0.RELEASE]
        at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:549) [spring-web-3.2.0.RELEASE.jar:3.
2.0.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [spring-web-3.2.0.RELEASE.
jar:3.2.0.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5063) [catalina.jar:7.0.61]
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5723) [catalina.jar:7.0.61]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [catalina.jar:7.0.61]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160) [catalina.jar:7.0.61]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.61]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.61]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.61]

**Comment by eugenp** [comment]
Hi - thanks for reaching out with this one. 
The problem here is Java 8 - the entire course project is tested only with Java 7 - and it looks like Java 8 introduced a bug for Spring: https://jira.spring.io/browse/SPR-10292
This can be fixed by upgrading Spring of course, but it may not be the only Java 8 related bug. My suggestion is to go with Java 7 to make sure everything works. 
Cheers, 
Eugen.

**Comment by jarema-antosz** [comment]
For me setting Java version as 1.7 in maven compiler plugin solved the problem:

<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
        </plugins>

**Comment by eugenp** [comment]
There still isn't any clear update on that issue on the backport for Spring 3.x - so I'm closing this one. 
If the backport does happen, I'll update the versions here to solve the problem and allow full use of Java 8. Cheers, 
Eugen.
